# Generated by Django 2.1.4 on 2019-01-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('in_stock', models.BooleanField(default=True)),
                ('quick_review', models.TextField()),
                ('product_description', models.TextField()),
                ('new_item', models.BooleanField(default=False)),
            ],
        ),
    ]
