# Generated by Django 2.1.4 on 2019-01-10 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
