# Generated by Django 2.1.4 on 2019-01-10 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterapp', '0007_auto_20190110_0745'),
        ('product_details', '0002_delete_productdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('in_stock', models.BooleanField(default=True)),
                ('quick_review', models.TextField()),
                ('product_description', models.TextField()),
                ('new_item', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterapp.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(default='no picture', upload_to='Product_Pictures')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterapp.Item')),
            ],
        ),
    ]
