# Generated by Django 2.1.4 on 2019-01-10 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0007_auto_20190110_0745'),
        ('product_details', '0003_productdetails_productpictures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDetails',
            new_name='ProductDetail',
        ),
        migrations.RenameModel(
            old_name='ProductPictures',
            new_name='ProductPicture',
        ),
    ]
