# Generated by Django 2.1.4 on 2019-01-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0004_auto_20190110_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpicture',
            name='product_image_type',
            field=models.CharField(default='images', max_length=10),
        ),
    ]
