# Generated by Django 2.1.4 on 2019-01-03 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Items', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('Category', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Slider_Pictures')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('SubMenu', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterapp.menu')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='SubMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterapp.SubCategory'),
        ),
    ]
