# Generated by Django 2.1.4 on 2019-01-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='no picture', upload_to='Items_Pictures'),
        ),
    ]
