# Generated by Django 2.1.4 on 2019-01-09 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0004_item_discount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discount_price',
            new_name='old_price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='special_price',
        ),
    ]
