# Generated by Django 2.1.4 on 2019-01-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0005_auto_20190109_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Items',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
