# Generated by Django 2.1.4 on 2019-01-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0006_auto_20190109_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='Items',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
